/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Data.DangNhapDB;
import javax.swing.JOptionPane;



/**
 *
 * @author Do Di
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setTitle("Đăng nhập");
        home();
        setLocation(600, 300);
        setSize(600, 460);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txMNV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LoiMaNV = new javax.swing.JLabel();
        loiMK = new javax.swing.JLabel();
        lbDN = new javax.swing.JLabel();
        txMK = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 178, 191));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Nhập");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(214, 40, 153, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 131, 101, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 201, 82, 17);

        txMNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txMNV);
        txMNV.setBounds(275, 129, 192, 23);

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(142, 287, 108, 25);

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(333, 287, 107, 25);

        LoiMaNV.setForeground(new java.awt.Color(204, 0, 51));
        LoiMaNV.setText("*");
        jPanel1.add(LoiMaNV);
        LoiMaNV.setBounds(472, 132, 8, 16);

        loiMK.setForeground(new java.awt.Color(204, 0, 51));
        loiMK.setText("*");
        jPanel1.add(loiMK);
        loiMK.setBounds(472, 199, 8, 16);

        lbDN.setForeground(new java.awt.Color(204, 0, 51));
        lbDN.setText("tài khoản hoặc mật khẩu không chính xác");
        jPanel1.add(lbDN);
        lbDN.setBounds(194, 231, 235, 16);

        txMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txMK);
        txMK.setBounds(275, 196, 192, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(kiem_tra_chuoi_nhap_vao())
        {
        char []arr=txMK.getPassword();
        String matkhau=new String(arr);
        if(DangNhapDB.Kiem_Tra_MK(txMNV.getText(), matkhau))
        {
            JOptionPane.showMessageDialog(null, "đăng nhập thành công");
            MainForm mn=new MainForm(txMNV.getText());
            mn.setVisible(true);
            this.dispose();
        }
        else
            lbDN.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void home()
    {
        lbDN.setVisible(false);
        LoiMaNV.setVisible(false);
        loiMK.setVisible(false);
    }
    
    public boolean kiem_tra_chuoi_nhap_vao()
    {
        home();
        char []arr=txMK.getPassword();
        String matkhau=new String(arr);
        int dem=0;
        if(txMNV.getText().equals(""))
        {
            LoiMaNV.setVisible(true);
            dem++;
        }
        if(matkhau.equals(""))
        {
            loiMK.setVisible(true);
            dem++;
        }
        return dem==0;
    }
    
    public static void main(String[] args) {
        DangNhap dn=new DangNhap();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoiMaNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDN;
    private javax.swing.JLabel loiMK;
    private javax.swing.JPasswordField txMK;
    private javax.swing.JTextField txMNV;
    // End of variables declaration//GEN-END:variables
}
