/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CTHDVE;
import Business.DieuKhienMuaVe;
import Business.GiaVe;
import Business.HoaDonVe;
import Business.KhachHang;
import Business.KiemTra;
import Business.LichChieu;
import Data.MuaVeDB;
import helper.JasperHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Do Di
 */
public class MuaVe extends javax.swing.JFrame implements ActionListener{
    private ArrayList<LichChieu> lc=MuaVeDB.lay_lich_chieu();
    private ArrayList<ArrayList> danh_sach_phim=DieuKhienMuaVe.lay_danh_sach_phim(lc);
    private ArrayList<ArrayList> Ngay_chieu;
    private ArrayList<ArrayList> GioChieu;
    private ArrayList<GiaVe> danh_sach_gia_ve=MuaVeDB.Lay_danh_sach_gia_ve();
    private JButton arr[];
    private int SoLuongPhim;
    private int Vi_tri_anh;
    private ArrayList<Integer> Danh_sach_ghe_da_mua;
    private String MaNV;
    private HoaDonVe hoadon;
    private int Vitrichuot=-1;
    JComboBox cb=new JComboBox();
    /**
     * Creates new form MuaVe
     */
    public MuaVe(String MaNV) {
        this.MaNV=MaNV;
        hoadon=new HoaDonVe((long)-1, MaNV);
        initComponents();
        setSize(1450, 1050);
        khoi_tao_ghe();
        khoitao();       
        them_combobox_vao_table();
        them_su_kien_button();
        AnDiemTichLuy();
    }

    public void khoitao()
    {
        
        SoLuongPhim=danh_sach_phim.size();
        if(SoLuongPhim!=0)
        {
            Chen_anh(danh_sach_phim.get(0));
            Vi_tri_anh=0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChinh = new javax.swing.JPanel();
        lbAnh = new javax.swing.JLabel();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        lbTenAnh = new javax.swing.JLabel();
        cbNgay = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGio = new javax.swing.JComboBox<>();
        pnSoDo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbTongTienVe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbGiamGia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bnCheck = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bn3 = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        lbLoi = new javax.swing.JLabel();
        btnMuaVe = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnChinh.setBackground(new java.awt.Color(102, 255, 255));
        pnChinh.setLayout(null);

        lbAnh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        lbAnh.setForeground(new java.awt.Color(255, 0, 51));
        lbAnh.setText("      Không có phim nào đang chiếu !!");
        lbAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.red, null, null));
        pnChinh.add(lbAnh);
        lbAnh.setBounds(390, 0, 640, 360);

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconRight.png"))); // NOI18N
        btnRight.setText("jButton3");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        pnChinh.add(btnRight);
        btnRight.setBounds(1080, 80, 90, 150);

        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconLeft.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        pnChinh.add(btnLeft);
        btnLeft.setBounds(250, 100, 90, 140);

        lbTenAnh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTenAnh.setForeground(new java.awt.Color(0, 51, 255));
        lbTenAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenAnh.setText("Tên Phim");
        pnChinh.add(lbTenAnh);
        lbTenAnh.setBounds(500, 370, 370, 40);

        cbNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNgayActionPerformed(evt);
            }
        });
        pnChinh.add(cbNgay);
        cbNgay.setBounds(400, 430, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Ngày Chiếu");
        pnChinh.add(jLabel1);
        jLabel1.setBounds(250, 430, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Giờ Chiếu");
        pnChinh.add(jLabel2);
        jLabel2.setBounds(740, 440, 90, 22);

        cbGio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioActionPerformed(evt);
            }
        });
        pnChinh.add(cbGio);
        cbGio.setBounds(870, 430, 180, 30);

        pnSoDo.setBackground(new java.awt.Color(0, 204, 153));
        pnSoDo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnSoDo.setLayout(new java.awt.GridLayout(10, 15));
        pnChinh.add(pnSoDo);
        pnSoDo.setBounds(70, 490, 690, 500);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Danh sách vé đã chọn");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnChinh.add(jLabel3);
        jLabel3.setBounds(1030, 480, 210, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Phim", "Số Ghế", "Ngày chiếu", "Giờ Chiếu", "Chọn loại vé", "Giá Vé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        pnChinh.add(jScrollPane2);
        jScrollPane2.setBounds(810, 520, 620, 290);

        jLabel4.setText("Tổng tiền vé");

        lbTongTienVe.setText("0");

        jLabel6.setText("Giảm giá");

        lbGiamGia.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tổng tiền");

        lbTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongTien.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongTienVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongTienVe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnChinh.add(jPanel1);
        jPanel1.setBounds(1140, 820, 290, 100);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SDT :");

        bnCheck.setText("Check");
        bnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCheckActionPerformed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb1.setText("Số điểm tích luỹ hiện có :");

        lb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb2.setText("0");

        bn3.setText("Sử dụng điểm tích luỹ");
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbLoi.setForeground(new java.awt.Color(255, 0, 51));
        lbLoi.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(bn3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnCheck))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb1)
                        .addGap(18, 18, 18)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT)
                    .addComponent(lbLoi)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(bn3))
        );

        pnChinh.add(jPanel2);
        jPanel2.setBounds(810, 820, 310, 100);

        btnMuaVe.setText("Mua Vé");
        btnMuaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaVeActionPerformed(evt);
            }
        });
        pnChinh.add(btnMuaVe);
        btnMuaVe.setBounds(860, 940, 110, 40);

        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        pnChinh.add(refresh);
        refresh.setBounds(1070, 940, 110, 40);

        jButton3.setText("Huỷ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnChinh.add(jButton3);
        jButton3.setBounds(1270, 940, 110, 40);

        getContentPane().add(pnChinh);
        pnChinh.setBounds(-30, -20, 1500, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
        if(SoLuongPhim!=0)
        {
           Vi_tri_anh=Vi_tri_anh-1;
           if(Vi_tri_anh==-1)
               Vi_tri_anh=SoLuongPhim-1;
            Chen_anh(danh_sach_phim.get(Vi_tri_anh));
        }
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        if(SoLuongPhim!=0)
        {
           Vi_tri_anh=Vi_tri_anh+1;
           if(Vi_tri_anh==SoLuongPhim)
               Vi_tri_anh=0;
            Chen_anh(danh_sach_phim.get(Vi_tri_anh));
        }
    }//GEN-LAST:event_btnRightActionPerformed

    private void cbNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNgayActionPerformed
        // TODO add your handling code here:
        if(cbNgay.getSelectedIndex()!=-1)
            Xu_kien_chon_ngay();
        else
        {
            cbGio.removeAllItems();
            GioChieu=null;
        }
    }//GEN-LAST:event_cbNgayActionPerformed

    private void cbGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioActionPerformed
        // TODO add your handling code here:
        if(cbGio.getSelectedIndex()!=-1)
        {
            pnSoDo.setVisible(true);
            int vitri=Lay_vi_tri_lich_chieu();
            DieuKhienMuaVe.hien_thi_ghe_trong(arr, hoadon,
                    lc.get(vitri).getMaLC());
        }
        else
        {
            pnSoDo.setVisible(false);
        }
    }//GEN-LAST:event_cbGioActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        Vitrichuot=table.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tableMouseReleased

    private void bnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCheckActionPerformed
        // TODO add your handling code here:
        if(KiemTra.kiem_tra_so(txtSDT.getText())==false)
        {
            lbLoi.setVisible(true);
        }
        else
        {
            KhachHang kh=MuaVeDB.lay_diem_tich_luy(txtSDT.getText());
            if(kh!=null)
            {
                hoadon.setKhachhang(kh);
                lbLoi.setVisible(false);
                lb2.setText(kh.getDiemTichLuy()+"");
                txtSDT.setEnabled(false);
                HienDiemTichLuy();
              
            }
            else
            {
                lbLoi.setVisible(true);
            }
        }
    }//GEN-LAST:event_bnCheckActionPerformed

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
        // TODO add your handling code here:
        hoadon.Giam_gia();
        hien_thi_tien();
    }//GEN-LAST:event_bn3ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        Refresh();
    }//GEN-LAST:event_refreshActionPerformed

    private void btnMuaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaVeActionPerformed
        // TODO add your handling code here:
        long bien_kiem_tra=hoadon.Luu_hoa_don_ve();
        System.out.println(bien_kiem_tra);
        if(bien_kiem_tra==-2)
        {
            JOptionPane.showMessageDialog(null, "bạn chưa chọn vé");
        }
        else if(bien_kiem_tra==-3)
        {
            JOptionPane.showMessageDialog(null, "bạn chưa chọn giá vé");
        }
        else if(bien_kiem_tra==-1)
        {
            System.out.println(hoadon.getMaNV());
            JOptionPane.showMessageDialog(null, "Lỗi ! Có thể vé đã được bán");
        }
        else
        {        
            String localDir = System.getProperty("user.dir");
            try {
                System.out.println("Đưa vào report");
                String filename=localDir+"\\src\\Report\\newReport1.jrxml"; 
                HashMap hs=new HashMap();
                hs.put("SoHD",BigDecimal.valueOf(bien_kiem_tra));
                ReportView p=new ReportView(hs,filename);
                p.setBounds(200, 200, 750, 500);
                p.setResizable(false);
                p.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                p.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(MuaVe.class.getName()).log(Level.SEVERE, null, ex);
            }           
            Refresh();   
        }
    }//GEN-LAST:event_btnMuaVeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaVe("NV001").setVisible(true);
            }
        });
    }

    public void Chen_anh(ArrayList<String> phim)
    {
        lbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/"
                +phim.get(0)+".jpg")));
        lbTenAnh.setText(phim.get(1));
        Xu_kien_chon_phim();
    }
    
    public void Xu_kien_chon_phim()
    {
        cbNgay.removeAllItems();
        cbGio.removeAllItems();
        Ngay_chieu=null;
        GioChieu=null;
        Ngay_chieu=DieuKhienMuaVe.lay_danh_ngay_chieu(lc,danh_sach_phim.get(Vi_tri_anh));
        them_ngay_chieu_vao_cb();
    }
    
    public void Xu_kien_chon_ngay()
    {
        cbGio.removeAllItems();;
        GioChieu=null;
        GioChieu=DieuKhienMuaVe.Lay_Gio_chieu(lc, Ngay_chieu.get(cbNgay.getSelectedIndex()));
        Them_gio_chieu_cao_cb();
        cbGio.setSelectedIndex(-1);
    }
    
    public void them_ngay_chieu_vao_cb()
    {
        int size=Ngay_chieu.size();
        for(int i=0;i<size;i++)
        {
            cbNgay.addItem((String) Ngay_chieu.get(i).get(0));
        }
        cbNgay.setSelectedIndex(-1);
    }
    
    public void Them_gio_chieu_cao_cb()
    {
        int size=GioChieu.size();
        for(int i=0;i<size;i++)
        {
            cbGio.addItem((String) GioChieu.get(i).get(0));
        }
    }
    
    public void khoi_tao_ghe()
    {
            arr=new JButton[150];
        int j=0;
        for(char a='A';a<'K';a++)    
        {
            for(int i=1;i<16;i++)
            {
                if(i<10)
                    arr[j]=new JButton(a+"0"+i);
                else
                    arr[j]=new JButton(a+""+i);
                arr[j].setBackground(new java.awt.Color(153, 0, 51));
                pnSoDo.add(arr[j]);
                arr[j].setFont(new java.awt.Font("Tahoma", 0, 10));
                j++;
            }
        }
    }
    
    public  void them_combobox_vao_table()
    {
        int size=danh_sach_gia_ve.size();
        for(int i=0;i<size;i++)
        {
            cb.addItem(danh_sach_gia_ve.get(i).getMaGV());
        }
        table.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cb));
        System.out.println("them_combobox_vao_table");
    }
    
    public void them_su_kien_button()
    {   
        System.out.println(cb);
        System.out.println(this);
        for(int i=0;i<150;i++)
        {
            arr[i].addActionListener(this);
        }
        cb.addActionListener(this);
        System.out.println(cb);
    }
    
    public int Lay_vi_tri_lich_chieu()
    {
        int vitri=Integer.parseInt((String) GioChieu.get(cbGio.getSelectedIndex()).get(1));
         return vitri;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn3;
    private javax.swing.JButton bnCheck;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnMuaVe;
    private javax.swing.JButton btnRight;
    private javax.swing.JComboBox<String> cbGio;
    private javax.swing.JComboBox<String> cbNgay;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbLoi;
    private javax.swing.JLabel lbTenAnh;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbTongTienVe;
    private javax.swing.JPanel pnChinh;
    private javax.swing.JPanel pnSoDo;
    private javax.swing.JButton refresh;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()!=cb) System.out.println("khác nhau");
        System.out.println(cb.getSelectedIndex());
        System.out.println(Vitrichuot);
        //if(ae.getSource()!=cb)
        //{   
            System.out.println("Lấy giá vé 2");
            System.out.println(cb.getSelectedIndex());
            System.out.println(Vitrichuot);
            System.out.println("CHECK 1");
            //click chuot khac -1 va gia tri nhan duoc khac -1
            if(Vitrichuot!=-1 && cb.getSelectedIndex()!=-1)
            {
            DefaultTableModel dtm= (DefaultTableModel) table.getModel();
            dtm.setValueAt(danh_sach_gia_ve.get(cb.getSelectedIndex()).getGia(), Vitrichuot, 5);
            hoadon.cap_nhat_gia_ve(danh_sach_gia_ve.get(cb.getSelectedIndex()),Vitrichuot);
            hien_thi_tien();
            System.out.println("Lấy giá vé 3");
            }
        //}
        System.out.println("CHECK 2");
        for(int i=0;i<150;i++)
        {
            if(ae.getSource()==arr[i])
            {
                DieuKhienMuaVe.Xu_ly_chon_ghe(lc.get(Lay_vi_tri_lich_chieu()), hoadon, arr[i], table);
                hien_thi_tien();
            }
        }
        System.out.println("CHECK 3");
    }
    
    public void hien_thi_tien()
    {
        lbTongTienVe.setText(hoadon.getTong_Tien_ve()+"");
        lbGiamGia.setText(hoadon.getGiamGia()+"");
        lbTongTien.setText(hoadon.getTong_tien()+"");
    }
    
    public void Refresh()
    {
        DefaultTableModel dtm= (DefaultTableModel) table.getModel();
        int size=hoadon.getCthdve().size();
        for(int i=size-1;i>-1;i--)
        {
            dtm.removeRow(i);
        }
        hoadon=new HoaDonVe((long)-1, MaNV);
        hien_thi_tien();
        AnDiemTichLuy();
        lbLoi.setVisible(false);
        txtSDT.setText("");
        txtSDT.setEnabled(true);
        
        khoitao();       
    }
    
    public void AnDiemTichLuy()
    {
        lb1.setVisible(false);
        lb2.setVisible(false);
        bn3.setVisible(false);
        lbLoi.setVisible(false);
    }
    public void HienDiemTichLuy()
    {
        lb1.setVisible(true);
        lb2.setVisible(true);
        bn3.setVisible(true);
    }
}
