/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.KiemTra;
import Data.Connect;
import Data.XoaSuaKH;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
//import java.text.SimpleDateFormat;


/**
 *
 * @author Do Di
 */
public class XoaSua extends javax.swing.JFrame {

    /**
     * Creates new form XoaSua
     */
    public XoaSua() {
        initComponents();
        setSize(750, 720);
        setResizable(false);
        
        AnGiaoDien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSDTKH = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbHoTen1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnUD = new javax.swing.JButton();
        btnDLT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        lbSDT = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbTien1 = new javax.swing.JLabel();
        lbTien2 = new javax.swing.JLabel();
        lbCMND = new javax.swing.JLabel();
        loiSDT = new javax.swing.JLabel();
        loiHT = new javax.swing.JLabel();
        loiDC = new javax.swing.JLabel();
        loiDT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thay đổi thông tin khách hàng");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(217, 23, 275, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("SDT khách hàng");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 85, 116, 29);

        txtSDTKH.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtSDTKH);
        txtSDTKH.setBounds(217, 86, 264, 26);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(524, 85, 99, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_customer_130.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 262, 130, 120);

        lbHoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHoTen1.setForeground(new java.awt.Color(51, 51, 255));
        lbHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHoTen1.setText("Trần Đình Đồng");
        getContentPane().add(lbHoTen1);
        lbHoTen1.setBounds(20, 395, 161, 26);

        jLabel3.setText("SDT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(227, 196, 24, 16);

        jLabel5.setText("Họ tên");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(227, 245, 37, 16);

        jLabel6.setText("CMND");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(227, 349, 50, 16);
        getContentPane().add(txtHoTen);
        txtHoTen.setBounds(334, 242, 348, 22);
        getContentPane().add(txtDiaChi);
        txtDiaChi.setBounds(334, 297, 348, 22);

        jLabel7.setText("Địa chỉ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(227, 300, 39, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Ngày mua gần nhất");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(75, 463, 148, 26);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Tổng điểm đã tích luỹ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(75, 527, 132, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Điểm tích luỹ hiện có");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(414, 527, 127, 17);

        btnUD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnUD.setText("Update");
        btnUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUDActionPerformed(evt);
            }
        });
        getContentPane().add(btnUD);
        btnUD.setBounds(172, 582, 84, 29);

        btnDLT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDLT.setText("Delete");
        btnDLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDLTActionPerformed(evt);
            }
        });
        getContentPane().add(btnDLT);
        btnDLT.setBounds(427, 582, 86, 29);

        jLabel9.setText("Ngày sinh");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(227, 405, 55, 16);
        getContentPane().add(txtdate);
        txtdate.setBounds(334, 399, 348, 22);

        lbSDT.setText("SDT");
        getContentPane().add(lbSDT);
        lbSDT.setBounds(334, 196, 348, 16);

        lbNgay.setForeground(new java.awt.Color(0, 51, 255));
        lbNgay.setText("Ngày");
        getContentPane().add(lbNgay);
        lbNgay.setBounds(230, 469, 151, 16);

        lbTien1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTien1.setForeground(new java.awt.Color(0, 51, 204));
        lbTien1.setText("Tiền");
        getContentPane().add(lbTien1);
        lbTien1.setBounds(230, 527, 131, 17);

        lbTien2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTien2.setForeground(new java.awt.Color(0, 0, 204));
        lbTien2.setText("Tiền");
        getContentPane().add(lbTien2);
        lbTien2.setBounds(578, 527, 91, 17);

        lbCMND.setText("CMND");
        getContentPane().add(lbCMND);
        lbCMND.setBounds(334, 349, 348, 16);

        loiSDT.setForeground(new java.awt.Color(255, 51, 51));
        loiSDT.setText("phải kiểu số");
        getContentPane().add(loiSDT);
        loiSDT.setBounds(217, 121, 207, 16);

        loiHT.setForeground(new java.awt.Color(255, 0, 51));
        loiHT.setText("*");
        getContentPane().add(loiHT);
        loiHT.setBounds(687, 242, 8, 16);

        loiDC.setForeground(new java.awt.Color(255, 0, 51));
        loiDC.setText("*");
        getContentPane().add(loiDC);
        loiDC.setBounds(687, 297, 8, 16);

        loiDT.setForeground(new java.awt.Color(255, 0, 51));
        loiDT.setText("*");
        getContentPane().add(loiDT);
        loiDT.setBounds(687, 399, 8, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        loiSDT.setVisible(false);
    if(txtSDTKH.getText().equals("")||KiemTra.kiem_tra_so(txtSDTKH.getText())==false)
    {
        AnGiaoDien("phải kiểu số");
    }
    else
    {
        
        
        String str="select hoten,cmnd,ngaysinh,diachi,ngaymuagannhat,"
                + "diemtichluy,tongdiemtichluy from khachhang where SDT='"+txtSDTKH.getText()+"'";
        try {
            
            Connection con=Connect.ket_noi_oracle();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(str);
            if(rs.next())
            {
                
                lbSDT.setText(txtSDTKH.getText());
                txtHoTen.setText(rs.getString(1));
                txtDiaChi.setText(rs.getString(4));
                lbCMND.setText(rs.getString(2));
                
                txtdate.setDate(rs.getDate(3));
                lbHoTen1.setText(rs.getString(1));
            
                if(rs.getDate(5)==null)
                    lbNgay.setText("null");
                else
                    lbNgay.setText(rs.getDate(5).toString());
                
                String tien=""+rs.getLong(6);
                lbTien1.setText(tien);
                String tien2=""+rs.getLong(7);
                lbTien2.setText(tien2);
                
                HienGiaoDien();
          
        
            }
            else
            {
                AnGiaoDien("không tìm thấy dữ liệu");
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUDActionPerformed
        // TODO add your handling code here:
        loiHT.setVisible(false);
        loiDC.setVisible(false);
        loiDT.setVisible(false);
        int dem=0;
        if(txtHoTen.getText().equals(""))
        {      
            dem++;
            loiHT.setVisible(true);
        }
        if(txtDiaChi.getText().equals(""))
        {
            dem++;
            loiDC.setVisible(true);
        }
        if(txtdate.getDate()==null)
        {
            dem++;
            loiDT.setVisible(true);
        }
        if(dem==0)
        {
        SimpleDateFormat date=new SimpleDateFormat("dd-MM-yyyy");
        String bdate=date.format(txtdate.getDate());
       if(XoaSuaKH.update_kh(lbSDT.getText(), txtHoTen.getText(), txtDiaChi.getText(),   bdate))
            JOptionPane.showMessageDialog(null,"update thanh cong");
        else
         System.out.println("update that bai");
        }
    }//GEN-LAST:event_btnUDActionPerformed

    private void btnDLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDLTActionPerformed
        // TODO add your handling code here:
        if(XoaSuaKH.delete_kh(lbSDT.getText()))
            JOptionPane.showMessageDialog(null, "xoa thanh cong");
        else
            JOptionPane.showMessageDialog(null,"tài khoản có thể đã bị xoá trước đó");
        AnGiaoDien();
        txtSDTKH.setText("");
    }//GEN-LAST:event_btnDLTActionPerformed

    private void AnGiaoDien()
    {
        lbSDT.setVisible(false);
        txtHoTen.setVisible(false);
        txtDiaChi.setVisible(false);
        txtdate.setVisible(false);
        lbCMND.setVisible(false);
        lbTien1.setVisible(false);
        lbTien2.setVisible(false);
        lbNgay.setVisible(false);
        lbHoTen1.setVisible(false);
        btnUD.setVisible(false);
        btnDLT.setVisible(false);
        loiSDT.setVisible(false);
        loiHT.setVisible(false);
        loiDC.setVisible(false);
        loiDT.setVisible(false);
    }
    
     private void AnGiaoDien(String loi)
     {
         loiSDT.setText(loi);
        loiSDT.setVisible(true);
        lbSDT.setVisible(false);
        txtHoTen.setVisible(false);
        txtDiaChi.setVisible(false);
        txtdate.setVisible(false);
        lbSDT.setVisible(false);
        lbCMND.setVisible(false);
        lbTien1.setVisible(false);
        lbTien2.setVisible(false);
        lbNgay.setVisible(false);
        lbHoTen1.setVisible(false);
        btnUD.setVisible(false);
        btnDLT.setVisible(false);
        loiHT.setVisible(false);
        loiDC.setVisible(false);
        loiDT.setVisible(false);
     }
     private void HienGiaoDien()
     {
         lbSDT.setVisible(true);
        txtHoTen.setVisible(true);
        txtDiaChi.setVisible(true);
        txtdate.setVisible(true);
        lbSDT.setVisible(true);
        lbCMND.setVisible(true);
        lbTien1.setVisible(true);
        lbTien2.setVisible(true);
        lbNgay.setVisible(true);
        lbHoTen1.setVisible(true);
        btnUD.setVisible(true);
        btnDLT.setVisible(true);
        loiHT.setVisible(false);
        loiDC.setVisible(false);
        loiDT.setVisible(false);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XoaSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XoaSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XoaSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XoaSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XoaSua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDLT;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCMND;
    private javax.swing.JLabel lbHoTen1;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTien1;
    private javax.swing.JLabel lbTien2;
    private javax.swing.JLabel loiDC;
    private javax.swing.JLabel loiDT;
    private javax.swing.JLabel loiHT;
    private javax.swing.JLabel loiSDT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDTKH;
    private com.toedter.calendar.JDateChooser txtdate;
    // End of variables declaration//GEN-END:variables
}
