/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Interface.MainForm;
import controller.BanThucPhamController;
import helper.JasperHelper;
import javax.swing.table.DefaultTableModel;
import model.ThucPham;
import model.GioHang;
import helper.StringHelper;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vi Yêu
 */
public class BanThucPhamForm extends javax.swing.JFrame {

    /**
     * Creates new form BanThucPhamForm
     */
    private String MaNV;
    private JFrame frame;
    private GioHang gioHang = new GioHang();

    public BanThucPhamForm(){};
    public BanThucPhamForm(String MaNV) {
        initComponents();
        HienThiMenu();
        setLocationRelativeTo(null);
        setBounds(200, 200, 1200, 700);
        setResizable(false);
        setTitle("Menu");
        this.MaNV=MaNV;
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên thực phẩm", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGioHang);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(12, 0, 560, 337);

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);
        btnXoa.setBounds(0, 498, 192, 63);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel2.add(btnThanhToan);
        btnThanhToan.setBounds(374, 498, 192, 63);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tổng cộng:  ");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorRemoved(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(184, 382, 111, 61);

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(lblTongTien);
        lblTongTien.setBounds(307, 344, 271, 136);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(471, 13, 600, 574);

        tblMenu.setForeground(new java.awt.Color(204, 0, 0));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thực phẩm", "Tên thực phẩm", "Đơn vị tính", "Giá (VND)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMenu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(12, 13, 452, 338);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(264, 511, 192, 63);

        jButton1.setText("Quay lại");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 534, 127, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int hangDuocChon = tblMenu.getSelectedRow();
        if (hangDuocChon == -1) {
            return;
        }

        String maThucPham = (String) tblMenu.getModel().getValueAt(hangDuocChon, 0);
        String tenThucPham = (String) tblMenu.getModel().getValueAt(hangDuocChon, 1);
        String donViTinh = (String) tblMenu.getModel().getValueAt(hangDuocChon, 2);
        double donGia = (double) tblMenu.getModel().getValueAt(hangDuocChon, 3);

        ThucPham thucPham = new ThucPham(maThucPham, tenThucPham, donViTinh, donGia);

        gioHang.KiemTraThem(thucPham, 1);
        ThemVaoGioHang();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int hangDuocChon = tblGioHang.getSelectedRow();
        if (hangDuocChon == -1) {
            return;
        }
        gioHang.remove(hangDuocChon);
        ThemVaoGioHang();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jLabel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorRemoved

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (gioHang.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Không có sản phẩm nào được chọn !");
            return;
        }
        BanThucPhamController.Luu(gioHang,this.MaNV);
        JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công! ");
        gioHang.clear();
        ThemVaoGioHang();
        String localDir = System.getProperty("user.dir");
        String s =localDir+"\\src\\jasperreport\\HoaDonTP.jrxml";
        JasperHelper.Report(s, null);

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        MainForm main = new MainForm(MaNV);
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    void HienThiMenu() {
        // lấy mô hình của jtable tblMenu, mô hình dùng để 
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();

        // xóa hết hàng trong bảng
        model.setRowCount(0);
        BanThucPhamController.HienThi(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanThucPhamForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanThucPhamForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanThucPhamForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanThucPhamForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BanThucPhamForm a=new BanThucPhamForm("NV010");
                a.setVisible(true);
            }
        });
    }

    private void ThemVaoGioHang() {
        // lấy mô hình của jtable tblMenu
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        // xóa hết hàng trong bảng
        model.setRowCount(0);
        // thêm tất cả những gì trong danh sách vừa lấy vào mô hình bảng
        BanThucPhamController.Them(gioHang, model);
        lblTongTien.setText(StringHelper.ChuyenDoi(gioHang.getTongTien()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
